name: my_cover_sdk
description: Mycover sdk
version: 0.0.1
homepage: https://github.com/ibuildgenius/mca-flutter-sdk

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^0.8.1

#  connectivity:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  assets:
    - assets/images/
